Added support for sending device MAC addresses as part of Device MfgInfo
fido-device-onboard/client-sdk-fidoiot pull request #287
Opened 2024-06-03 08:05 UTC by shrikant1407

Added support for sending device MAC addresses as part of Device Mfg Info

2024-06-04 04:47 UTC, DukeDavis12 submitted a review, later dismissed

2024-06-04 09:02 UTC, SSWAMIN1SSS commented
We store the IP Address in a file within data/mac_address.bin which is being sent in DI AppStart along with DeviceInformation which is being added to Manufacturer_voucher's macaddress.
Can we add input validation whether the file contains only MAC Address by checking all file entries are in a valid MAC Format.

2024-06-05 08:24 UTC, DukeDavis12 approved these changes

2024-06-06 10:40 UTC, Sai-Anudeep47 approved these changes

2024-06-10 06:37 UTC, DukeDavis12 requested changes
Please fix the build issues

2024-06-14 05:35 UTC, DukeDavis12 approved these changes

2024-06-14 05:40 UTC, KiranSukhavasi approved these changes

2024-06-14 05:42 UTC, merged